#!/usr/bin/env bash -e

starttmux() {
    local hosts=( $@ )

    tmux new-window "ssh ${hosts[0]}"
    unset hosts[0];
    for i in "${hosts[@]}"; do
        tmux split-window -h  "ssh $i"
        tmux select-layout tiled > /dev/null
    done
    tmux select-pane -t 0
    tmux set-window-option synchronize-panes on > /dev/null
}

if [ ${#*} -eq 0 ]; then
    echo "No hosts were specified."
    exit 1
fi

if [ ! -z "$TMUX" ]; then
    starttmux $@
else
    if [ ${#*} -eq 1 ]; then
        ssh $@
    else
        i2cssh $@
    fi
fi
