#!/bin/bash

HOST=$1
if [ -z ""$HOST ]
then
	echo "Usage: "
	echo "    $0 <HOST>"
	exit 1
fi

COLUMNS=`tput cols`
LINES=`tput lines`
TERM=xterm
kubectl exec -it "${HOST}" -- env COLUMNS=$COLUMNS LINES=$LINES TERM=$TERM bash

